### ISSUE TITLE
Device /home/<user>/d not found.

### ISSUE THREAD

**Issue by oloc** [mrlesmithjr/ansible-manage-lvm#12]
Regression with the very last commit.
```
TASK [ansible-manage-lvm : manage_lvm | creating new LVM volume group(s)] **************************************************************************************************************
failed: [my-server] (item={u'lvnames': [{u'lvname': u'usr', u'create': True, u'filesystem': u'xfs', u'mntp': u'/usr', u'mount': True, u'size': u'2g'}, {u'lvname': u'var', u'create': True, u'filesystem': u'xfs', u'mntp': u'/var', u'mount': True, u'size': u'3g'}, {u'lvname': u'var_log', u'create': True, u'filesystem': u'xfs', u'mntp': u'/var/log', u'mount': True, u'size': u'2g'}], u'vgname': u'vg01', u'disks': u'/dev/vda2', u'create': True}) => {"failed": true, "item": {"create": true, "disks": "/dev/vda2", "lvnames": [{"create": true, "filesystem": "xfs", "lvname": "usr", "mntp": "/usr", "mount": true, "size": "2g"}, {"create": true, "filesystem": "xfs", "lvname": "var", "mntp": "/var", "mount": true, "size": "3g"}, {"create": true, "filesystem": "xfs", "lvname": "var_log", "mntp": "/var/log", "mount": true, "size": "2g"}], "vgname": "vg01"}, "msg": "Device /home/oloc/d not found."}
```

**Comment by oloc** [comment]
As I understand I need to convert my playbooks from 
```
  - role: ansible-manage-lvm
    manage_lvm: true
    lvm_groups:
    - vgname: vg01
      disks: "{{ disks }}"
```
to

```
  - role: ansible-manage-lvm
    manage_lvm: true
    lvm_groups:
    - vgname: vg01
      disks:
      - "{{ disks }}"
```

**Comment by mrlesmithjr** [comment]
@oloc Sorry about that. Trying to make this more efficient. Below is an example of the way the new vars work:
```yaml
  - role: ansible-manage-lvm
    manage_lvm: true
    lvm_groups:
     - vgname: vg01
       disks:
         - /dev/sda5
         - /dev/sdc
         - /dev/sdd
```

If this does not work for you there are previous [releases](https://github.com/mrlesmithjr/ansible-manage-lvm/releases) which use the old way. Hopefully one of these will work for you.
