### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by johsod** [mrlesmithjr/ansible-manage-lvm#16]
Hi,

Thanks for a great ansible role, very useful! However there is one feature that I'd like to have included. The ability to partition the disks. As it is now the role is assuming the disks are partitioned and ready to be used.

Perhaps the variable declaration could look something like this:
```
- hosts: test-nodes
  vars:
    lvm_groups:
      - vgname: test-vg
        disks:
          - device: /dev/sdb
            number: 1
          - device: /dev/sdc
            number: 2
        create: true
        lvnames:
          - lvname: test_1
            size: 5g
            create: true
            filesystem: ext4
            mount: true
            mntp: /mnt/test_1
          - lvname: test_2
            size: 10g
            create: true
            filesystem: ext4
            mount: true
            mntp: /mnt/test_2
    manage_lvm: true
    pri_domain_name: 'test.vagrant.local'
  roles:
    - role: ansible-manage-lvm
  tasks:
```

and corresponding part in the role:

```
- name: Partition disk
  parted:
    device: "{{ item.1.device }}"
    number: "{{ item.1.number }}"
    flags: [lvm]
    state: present
  with_subelements:
    - "{{ lvm_groups }}"
    - disks
  register: parted
```

Unfortunately I dont know how to create a list out of that to be used by the pvs option in the lvg module.

Regards,

/Johan
