### ISSUE TITLE
XFS Filesystem are not created 

### ISSUE THREAD

**Issue by cholletk** [mrlesmithjr/ansible-manage-lvm#66]
**Describe the bug**
XFS filesystem is not created

**To Reproduce**
Use the following lvm_groups variable
```
lvm_groups:
  - vgname: test_vg
    disks:
      - /dev/sdb
    create: true
    lvnames:
      - lvname: test_lv
        size: 100%FREE
        create: true
        filesystem: xfs
        mount: true
        mntp: /test
```

**Expected behavior**
xfs_info command (in create_fs) never fail in an xfs root

**Additional context**
Test done on centos 7
