### ISSUE TITLE
Partition resize ?

### ISSUE THREAD

**Issue by Slowdive-Aideron** [mrlesmithjr/ansible-manage-lvm#83]
I might be blind, but i don't see any task that extends the actual partition. 
My case: deploying an azure rhel8 image from the marketplace . It's 64Gib big, of course i want a bigger odsdisk so i provision with 120GiB 

The way i understand it the first step would be to extend the actual partition for ex. /dev/sda2 and then go an pvresize , vgresize etc. 

There is a community parted ansible module for this : 

```
- name: Read device information (always use unit when probing)
  community.general.parted: device=/dev/sdb unit=MiB
  register: sda_info

- name: Extend an existing partition to fill all available space
  become: true
  community.general.parted:
    device: /dev/sda
    number: "{{ sda_info.partitions | length }}"
    part_end: "99%"
    resize: true
    label: gpt
    state: present
  tags:
  - resizePart
 
```
